// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import TickerViewer__ComponentController from "./ticker_viewer/component_controller.js"
application.register("ticker-viewer--component", TickerViewer__ComponentController)
