development:
  adapter: redis
  url: redis://tickerizer_redis:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: tickerizer_production
